import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Generated by FlutterFire CLI. Android-only configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJgFprqN9OYboyO8C_mNA92FAH7odmME',
    appId: '1:1003461463162:android:725c4852c7e0f2f3032b4b',
    messagingSenderId: '1003461463162',
    projectId: 'ppqa-snag-logger',
    storageBucket: 'ppqa-snag-logger.firebasestorage.app',
  );
}
